---
driver:
  name: vagrant
  driver_config:
    box: "boxcutter/ubuntu1404"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04


suites:
  - name: default
    run_list:

      - recipe[vm::default]

    attributes:
