driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  client_rb:
    add_formatter: doc

platforms:
- name: ubuntu-14.04
  driver_config:
    box: bento/ubuntu-14.04
    customize:
      cpus: 8
      memory: 4096
    network:
      - ["forwarded_port", {guest: 9200, host: 9200}]
      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[elk-stack::default]
